---
title: "Simulando con la distribución Bernoulli"
author: "SMandujanoR"
date: "10/10/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

Ejemplo para entender la distribución Bernoulli, a partir del código de Diego Lizcano.

## Parámetros a simular

En este ejemplo se puede variar el número de simulaciones y la probabilidad del evento (probabilidad de detección en los HMs).

```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Número de simulaciones:", choices = c(1, 10, 20, 40, 80, 160, 320, 640, 1280), selected = 10),
  
  sliderInput("bw_adjust", label = "Probabilidad del evento:", min = 0.1, max = 1, value = 0.5, step = 0.1)
)

renderPlot({
 
daber <- data.frame(estimado=rbinom(input$n_breaks, 1, input$bw_adjust))

ggplot(daber, aes(x=estimado)) + 
    geom_histogram(aes(y=..density..),
    binwidth=.1, 
    colour="black", fill="white") + 
    geom_vline(aes(xintercept=mean(estimado, na.rm=T)), 
    color="blue", 
    linetype="dashed", size=1) 
})
```

## Fabulosa la aplicación Shiny...!


